comisiones/urls.py
from django.urls import path
from .views import listar_comisiones, registro_comision, edicion_comision

urlpatterns = [
    path('', listar_comisiones, name='comisiones'),
    path('registro_comision/', registro_comision, name='registro_comision'),
    path('edicion_comision/<id>', edicion_comision, name='edicion_comision'),
]

terratur/urls.py
from cgitb import html
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.panel, name='panel'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('template/', views.template_dashboard, name='template_dashboard'),
    path('asesores/', include('terratur_app.urls')), #esta ruta esta asociada a la ruta urls creada en la carpeta terratur_app
    path('comisiones/', include('comisiones.urls')),
    #path('comisiones/', views.comisiones, name='comisiones'),
    # path('listar_comisiones/', views.listar_comisiones, name='listar_comisiones'),
    # path('registro_comision/', views.registro_comision, name='registro_comision'),
    # path('edicion_comision/', views.edicion_comision, name='edicion_comision/'),

]

terratur_app/models.py
from django.db import models

# Create your models here.

# Un modelo es una tabla en la DB y cada uno de los atributos representa un campo en la base de datos

# Un modelo se define con una clase en python. Las clases usan una notación CamelCase

class GerenteDeCuenta(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Nombres')
    last_name = models.CharField(max_length=50, verbose_name='Apellidos')
    email = models.EmailField(max_length = 254, verbose_name='Correo')

    def __str__(self):
        return self.first_name

class Meta:
    verbose_name = 'Gerente de cuenta'
    verbose_name = 'Gerentes de cuenta'
    db_table = 'gerente_de_cuenta'
    ordering = ['id']

class Asesor(models.Model):
    #asesor_id = ['id']
    first_name = models.CharField(max_length=50, verbose_name='Nombres')
    last_name = models.CharField(max_length=50, verbose_name='Apellidos')
    phone = models.IntegerField(verbose_name='Celular')
    email = models.EmailField(max_length = 254, verbose_name='Correo')
    #commission = models.IntegerField(verbose_name='Comisión')
    advisory_status = models.CharField(max_length=10, verbose_name='Estado Asesor')
    GerenteDeCuenta = models.ForeignKey(GerenteDeCuenta, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

class Meta:
    verbose_name = 'Asesor'
    verbose_name = 'Asesores'
    db_table = 'asesor'
    ordering = ['id']

#objs = [Asesor(first_name=asesor) for asesor in Asesor]
# Asesor.objects.bulk_create(objs)    

elegir_destino = [
    (1, 'Villa de Leyva'),
    (2, 'Lago de Tota'),
    (3, 'Hacienda Napoles'),
    (4, 'Desierto de la Tatacoa'),
    (5, 'Eje Cafetero'),
    (6, 'Medellin y Guatapé'),
    (7, 'Santander'),
    (8, 'Cartagena'),
    (9, 'Guajira'),
    (10, 'San Andres'),
    (11, 'Santa Marta'),
    (12, 'Amazonas'),
    (13, 'Bahía Solano'),
    (14, 'Capurgana'),
    (15, 'Ciudad Perdida'),
    (16, 'Caño Cristales'),
    (17, 'Deportes Extremos Nimaima'),
    (18, 'Nevado del Cocuy'),
    (19, 'Cuatrimotos Villa de Leyva'),
    (20, 'Parapente Villavicencio'),
]

estado_comision = [
    (1, 'Pendiente'),
    (2, 'Pagada'),
    (3, 'Anulada')
]

class Comision(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    Asesor = models.ForeignKey(Asesor, null=False, blank=False, on_delete=models.CASCADE)
    destino = models.IntegerField(null=False, blank=False, choices=elegir_destino)
    total_sale = models.DecimalField(max_digits = 19, decimal_places = 2, verbose_name='Valor venta')
    advisory_commission = models.IntegerField(verbose_name='Comisión')
    commission_to_pay = models.DecimalField(max_digits = 19, decimal_places = 2, verbose_name='Comisión a pagar')
    commission_status = models.IntegerField(null=False, blank=False, choices=estado_comision, default=1, verbose_name='Estado de comisión')
    # estado_comision = models.CharField(max_length=10, verbose_name='Estado de comisión')

    # @property
    # def calculo_comision(self):
    #     return((self.total_sale * self.advisory_commision) * 100)

    # def save(self):
    #     self.commission_to_pay = self.calculo_comision
    #     super(Comision, self).save()

    def __str__(self):
        return str(self.Asesor)          

class Meta:
    verbose_name = 'Comision'
    verbose_name = 'Comisiones'
    db_table = 'comision'
    ordering = ['id']



comisiones/forms.py
from django import forms
from django.forms import ModelForm
#from .models import Comision
from terratur_app.models import Comision


class ComisionesForm(forms.ModelForm):
    class Meta:
        model = Comision
        #fields = ['Asesor', 'destino', 'total_sale', 'advisory_commission', 'commission_to_pay', 'commission_status']
        fields = '__all__'
        widgets = {
            'Asesor': forms.Select(attrs={'class': 'form-select mb-2', 'readonly':'readonly'}),
            'destino': forms.Select(attrs={'class': 'form-select mb-2'}),
            'total_sale': forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Ingresa el valor de venta' }),
            'advisory_commission': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'commission_to_pay': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'commission_status': forms.Select(attrs={'class': 'form-select mb-2'}),
            #'estado_comision' : forms.Select(attrs={'class': 'form-select mb-2'}),
        }


class ComisionesEditarForm(forms.ModelForm):
    class Meta:
        model = Comision
        fields = ['Asesor', 'destino', 'total_sale', 'advisory_commission', 'commission_to_pay', 'commission_status']
        #fields = '__all__'
        widgets = {
            'Asesor': forms.Select(attrs={'class': 'form-select mb-2', 'readonly':'readonly'}),
            'destino': forms.Select(attrs={'class': 'form-select mb-2'}),
            'total_sale': forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Ingresa el valor de venta' }),
            'advisory_commission': forms.TextInput(attrs={'class': 'form-control mb-2', 'readonly':'readonly'}),
            'commission_to_pay': forms.TextInput(attrs={'class': 'form-control mb-2'}),
            'commission_status': forms.Select(attrs={'class': 'form-select mb-2'}),
            #'estado_comision' : forms.Select(attrs={'class': 'form-select mb-2'}),
        }

comisiones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from terratur_app.models import Comision
from .forms import ComisionesForm, ComisionesEditarForm

def listar_comisiones(request):
    comisiones = Comision.objects.all()
    return render(request, 'comisiones.html', {"comisiones": comisiones})

def registro_comision(request):
    if request.method == 'GET':
        return render(request, 'registro_comision.html', {"form": ComisionesForm})
    else:
        form = ComisionesForm(request.POST)
        if form.is_valid():
            nueva_comision = form.save(commit=False)
            nueva_comision.save()
        return redirect('comisiones')

def edicion_comision(request, id):

    comision = get_object_or_404(Comision, id=id)

    data = {
        'form': ComisionesEditarForm(instance=comision)
    }

    if request.method == 'POST':
        formulario = ComisionesEditarForm(data=request.POST, instance=comision, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="comisiones")
        data["form"] = formulario    

    return render(request, "edicion_comision.html", data)



templates/asesores.html
{% extends "template_dashboard.html" %}

{% block title %} Asesores registrados {% endblock %}
    
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-12 pt-5">
                <button class="btn btn-primary mb-3" type="submit" data-bs-toggle="modal" data-bs-target="#contenedor-modal-registro-asesor"><i class="fa-solid fa-user-plus"><a style="font-family: montserrat"> Registrar asesor</a></i></button>
                <table class="table">                   
                    <tbody>                       
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Apellidos</th>
                                <th scope="col">Celular</th>
                                <th scope="col">Correo</th>
                                <!-- <th scope="col">Porcentaje comisión</th> -->
                                <th scope="col">Estado</th>
                                <th scope="col">Editar</th>
                                <th scope="col">Eliminar</th>
                            </tr>
                        </thead>
                        {% for Asesor in asesores %}
                        <tr>
                            <!-- <th scope="row">{{Asesor.id}}</th> -->
                            <td><b>{{forloop.counter}}</b></td>
                            <td>{{Asesor.first_name}}</td>
                            <td>{{Asesor.last_name}}</td>
                            <td>{{Asesor.phone}}</td>
                            <td>{{Asesor.email}}</td>
                            <!-- <td>{{Asesor.commission}}</td> -->
                            <td>{{Asesor.advisory_status}}</td>                        
                            <!-- <td><a class="icono-editar-asesor" href="modificar_asesor/{{ Asesor.id }}"><i class="fa-solid fa-pen-to-square" data-bs-toggle="modal" data-bs-target="#contenedor-modal-editar-asesor{{ Asesor.id }}"></i></a></td> -->
                            <td><a class="icono-editar-asesor" href="#"><i class="fa-solid fa-pen-to-square" data-bs-toggle="modal" data-bs-target="#contenedor-modal-editar-asesor{{ Asesor.id }}"></i></a></td>
                            <td><a class="icono-eliminar-asesor" href="#"><i class="fa-solid fa-trash-can" data-bs-toggle="modal" data-bs-target="#contenedor-modal-eliminar-asesor{{ Asesor.id }}"></i></a></td>
                        </tr>
                        {% empty %}
                        <div class="col-12 col-md-6 offset-md-3 pt-5">
                            <h2 class="mb-5">¡Aun no hay asesores registrados!</h2>
                        </div>
                        {% endfor %}            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>


<!-- Contenido Modal Formulario para registro de asesores -->
<div class="modal fade" id="contenedor-modal-registro-asesor" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aquí puedes registrar los datos de los asesores</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'nuevo_asesor' %}" method="POST" id="formulario-de-registro-asesores-modal" class="container-form-registro needs-validation p-5" novalidate>
                    {% csrf_token %}
                    <!-- <div class="row"> -->
                    <div class="row">
                        <div class="md-4 input-group-lg mb-3">
                            <label for="name" class="form-label">Nombre</label>
                            <input name="first_name" type="text" class="form-control needs-validation" required novalidate id="name" placeholder="Ingresa el nombre">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="name" class="form-label">Apellidos</label>
                            <input name="last_name" type="text" class="form-control needs-validation" required novalidate id="name" placeholder="Ingresa el apellido">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Celular</label>
                            <input name="phone" type="text" class="form-control needs-validation" required id="lastname" placeholder="Ingresa el numero de celular">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>
            
                        <div class="md-3 input-group-lg mb-3">
                            <label for="inputEmail" class="form-label">Correo</label>
                            <input name="email" type="email" class="form-control needs-validation" required id="inputEmail" placeholder="Ingresa el correo electronico">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <!-- <div class="md-3 input-group-lg mb-3">
                            <label for="name" class="form-label">Tasa de comisión</label>
                            <input name="commission" type="text" class="form-control needs-validation" required novalidate id="name" placeholder="Ingresa la comisión a pagar a este asesor ">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div> -->

                        <div class="md-3 input-group-lg mb-3">
                            <label for="disabledSelect" class="form-label">Estado del asesor</label>
                            <select name="advisory_status" id="disabledSelect" class="form-select">
                                <option value="Activo">Activo</option>
                                <option value="Inactivo">Inactivo</option>
                            </select>
                        </div> 
                        
                        <div class="d-grid boton-formulario-registro">
                            <button class="btn btn-primary btn-lg" type="submit">Confirmar</button>
                            <button type="button" class="btn btn btn-outline-secondary mt-4 btn-lg" data-bs-dismiss="modal">Cancelar</button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Fin formulario registro asesores -->


<!-- Contenido Modal Formulario para editar asesores -->
{% for Asesor in asesores %}
<div class="modal fade" id="contenedor-modal-editar-asesor{{ Asesor.id }}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aquí puedes editar los datos de los asesores</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="editar_asesor/{{Asesor.id}}" method="POST" id="formulario-de-editar-asesores-modal{{ Asesor.id }}" class="container-form-registro needs-validation p-5" novalidate>
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{Asesor.id}}">
                    <div class="row">
                        <div class="md-4 input-group-lg mb-3">
                            <label for="name" class="form-label">Nombre</label>
                            <input name="first_name" value="{{Asesor.first_name}}" type="text" class="form-control needs-validation" required novalidate id="first_name" placeholder="Ingresa el nombre">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="name" class="form-label">Apellidos</label>
                            <input name="last_name" value="{{Asesor.last_name}}" type="text" class="form-control needs-validation" required novalidate id="last_name" placeholder="Ingresa el apellido">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Celular</label>
                            <input name="phone" value="{{Asesor.phone}}" type="text" class="form-control needs-validation" required id="phone" placeholder="Ingresa el numero de celular">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>
            
                        <div class="md-3 input-group-lg mb-3">
                            <label for="inputEmail" class="form-label">Correo</label>
                            <input name="email" value="{{Asesor.email}}" type="email" class="form-control needs-validation" required id="email" placeholder="Ingresa el correo electronico">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <!-- <div class="md-3 input-group-lg mb-3">
                            <label for="name" class="form-label">Tasa de comisión</label>
                            <input name="commission" value="{{Asesor.commission}}"type="text" class="form-control needs-validation" required novalidate id="commission" placeholder="Ingresa la comisión a pagar a este asesor ">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div> -->

                        <div class="md-3 input-group-lg mb-3">
                            <label for="disabledSelect" class="form-label novalidate">Estado del asesor</label>
                            <select name="advisory_status" value="{{Asesor.last_name}}" id="advisory_status" class="form-select">
                                <option value="Activo">Activo</option>
                                <option value="Inactivo">Inactivo</option>
                            </select>
                        </div> 
                        
                        <div class="d-grid boton-formulario-registro">
                            <!-- <a class="btn btn-primary btn-lg mt-4" href="modificar_asesor/{{Asesor.id}}" type="submit">Confirmar</a> -->
                            <button class="btn btn-primary btn-lg" type="submit">Confirmar</button>                    
                            <button type="button" class="btn btn btn-outline-secondary mt-4 btn-lg" data-bs-dismiss="modal">Cancelar</button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %} 
<!-- fin formulario editar asesores -->

<!-- Contenido Modal Formulario para eliminar registro de asesores -->
{% for Asesor in asesores %}
<div class="modal fade" id="contenedor-modal-eliminar-asesor{{ Asesor.id }}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar registro de asesor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">                
                <div class="d-grid boton-formulario-registro">
                    <h5 class="text-center">Si eliminas el registro esta acción no se podra modificar y perderás los datos de contacto del asesor </h5>
                    <a class="btn btn-primary btn-lg mt-4" href="delete_asesor/{{Asesor.id}}" type="submit">Eliminar registro</a>
                    <!-- <a class="btn btn-primary btn-lg mt-4" type="submit">Eliminar registro</a>               -->
                    <button type="button" class="btn btn btn-outline-secondary mt-4 btn-lg" data-bs-dismiss="modal">Cancelar</button>
                </div>                
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/comisiones.html
{% extends "template_dashboard.html" %}

{% block title %} Comisiónes Asesores {% endblock %}
    
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-12 pt-5">
                <button class="btn btn-primary mb-3"><i class="fa-solid fa-chart-simple"><a class="text-decoration-none text-light" href="{% url 'registro_comision' %}" style="font-family: montserrat"> Registrar Comisión</a></i></button>
                <table class="table">
                    <tbody>
                        <thead>
                            <tr>
                            <th scope="col">No</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Asesor</th>
                            <th scope="col">Destino</th>
                            <th scope="col">Total</th>
                            <th scope="col">Tasa comisión</th>
                            <th scope="col">Comisión</th>
                            <th scope="col">Estado comisión</th>
                            <th scope="col">Editar</th>
                            </tr>
                        </thead>
                        {% for Comision in comisiones %}
                        <tr>
                            <td><b>{{forloop.counter}}</b></td>
                            <td>{{Comision.fecha_creacion}}</td>
                            <td>{{Comision.Asesor}}</td>
                            <td>{{Comision.get_destino_display}}</td>
                            <td>{{Comision.total_sale}}</td>
                            <td>{{Comision.advisory_commission}}</td>
                            <td>{{Comision.commission_to_pay}}</td>
                            <td>{{Comision.get_commission_status_display}}</td>
                            <!-- <td><button type="submit" class="btn btn-sm insignia-de-estado-pendiente" href="#" data-bs-toggle="modal" data-bs-target="#contenedor-modal-editar-comision{{ Comision.id }}">Editar</button></td> -->
                            <td><a href="{% url 'edicion_comision' Comision.id %}" class="btn btn-sm insignia-de-estado-pendiente">Editar</a></td>                        
                        </tr>
                        {% empty %}
                        <div class="col-12 col-md-6 offset-md-3 pt-5">
                            <h2 class="mb-5">¡Aun no hay comisiones registrados!</h2>
                        </div>
                        {% endfor %}            
                    </tbody>
                </table>    
            </div>
        </div>
    </div>
</section>


<!-- Contenido Modal Formulario para editar Comisiones -->
<!-- {% for Comision in comisiones %}
<div class="modal fade" id="contenedor-modal-editar-comision{{ Comision.id }}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aquí puedes editar las comisiones</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="edicion_comision/{{Comision.id}}" method="POST" id="formulario-de-editar-asesores-modal{{ Comision.id }}" class="container-form-registro needs-validation p-5" novalidate>
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{Comision.id}}">
                    <div class="row">
                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Asesor</label>
                            <input readonly name="Asesor" value="{{Comision.Asesor}}" type="text" class="form-control needs-validation" required id="Asesor" placeholder="Nombre asesor">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Destino</label>
                            <input readonly name="destino" value="{{Comision.get_destino_display}}" type="text" class="form-control needs-validation" required id="destino">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Valor venta</label>
                            <input name="total_sale" value="{{Comision.total_sale}}" type="text" class="form-control needs-validation" required id="total_sale" placeholder="Ingresa el valor de la venta">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Comisión</label>
                            <input readonly name="advisory_commission" value="{{Comision.advisory_commission}}" type="text" class="form-control needs-validation" required id="advisory_commission" placeholder="Ingresa el valor de la venta">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>
            
                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Comisión a pagar</label>
                            <input readonly name="commission_to_pay" value="{{Comision.commission_to_pay}}" type="text" class="form-control needs-validation" required id="commission_to_pay" placeholder="Ingresa el valor de la venta">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>

                        <div class="md-3 input-group-lg mb-3">
                            <label for="lastname" class="form-label">Estado de la comisión</label>
                            <input name="commission_status" value="{{Comision.get_commission_status_display}}" type="text" class="form-control needs-validation" required id="commission_status" placeholder="Ingresa el valor de la venta">
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">Completa los datos</div>
                        </div>                            
                        <div class="d-grid boton-formulario-registro">
                            <button class="btn btn-primary btn-lg" type="submit">Confirmar</button>                    
                            <button type="button" class="btn btn btn-outline-secondary mt-4 btn-lg" data-bs-dismiss="modal">Cancelar</button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}  -->
<!-- fin formulario editar comisiones -->
{% endblock %}

templates/edicion_comision.html
{% extends "template_dashboard.html" %}

{% block title %} Editar comisión {% endblock %}
    
{% block content %}
<section class="mt-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                    <h2 class=" mt-4 titulo-form-registro text-center">Editar comisión</h2>
                <div class="col-12 col-md-6 offset-md-3 pt-5">
                    <form method="POST" id="formulario-edicion-comision" class="container-form-registro needs-validation p-5" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{Comision.id}}">
                        {{form}}                            
                            <div class="d-grid boton-formulario-registro">
                                <!-- <a class="btn btn-primary btn-lg mt-4" href="edicion_comision/{{Comision.id}}" type="submit">Confirmar</a> -->
                                <button class="btn btn-primary btn-lg" type="submit">Confirmar</button>
                                <a  href="{% url 'comisiones' %}" asp-action="Listar" asp-controller="Dashboard" class="btn btn-outline-secondary btn-lg mt-2 mb-5 btn-ver-lista-de-asesores">Cancelar</a>                              
                            </div>                        
                        </div>
                    </form>
            </div>
         </div>                  
    </div>
</section>
{% endblock %}